version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: fatik-adminer_web_1
      APP_PORT: 8080

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: main
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql

  web:
    image: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db