version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: fatik-phpmyadmin_web_1
      APP_PORT: 80

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_PASSWORD}
      MYSQL_DATABASE: main
      MYSQL_USER: app
      MYSQL_PASSWORD: ${APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/mysql:/var/lib/mysql

  web:
    image: lscr.io/linuxserver/phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: app
      PMA_PASSWORD: ${APP_PASSWORD}
    depends_on:
      - db